/*
** EPITECH PROJECT, 2023
** Arcade
** File description:
** MagicValue
*/

#pragma once


#define TO_FLOAT(x) static_cast<float>(x)
#define TO_INT(x) static_cast<int>(x)

#define NIBBLER_HEAD "NIBBLER_HEAD"
#define NIBBLER_HEAD_SPRITE_COMP "NIBBLER_HEAD_SPRITE_COMP"
#define MOVE_INPUT_COMPS "MOVE_INPUT_COMPS"

#define NUMBER_COLUMNS 50
#define NUMBER_LINES 10
#define SCREEN_WIDTH 1920
#define SCREEN_HEIGHT 1080
#define CASE_SIZE_WIDTH (TO_FLOAT(SCREEN_WIDTH) / NUMBER_COLUMNS)
#define CASE_SIZE_HEIGHT (TO_FLOAT(SCREEN_HEIGHT) / NUMBER_LINES)

#define NIBBLER_MOVE_PER_DTIME 0.5

#define FORWARD_KEY "direction"
#define EATED_EVENT "EATED"
#define RESTART_EVENT "RESTART"
#define APPLE_ENTITY "Apple"
#define APPLE_SPRITE_COMP "apple"
#define NIBBLER_MAP_ID "NIBBLER_map"
#define NIBBLER_WALL_ID "NIBBLER_wall"
#define NIBBLER_PADDING_WINDOW_X 535
#define NIBBLER_PADDING_WINDOW_Y 165
#define PARCELL_SIZE 50
#define MAP_PARCELLS_X 17
#define MAP_PARCELLS_Y 15
#define MAP_RIGHT (NIBBLER_PADDING_WINDOW_X + PARCELL_SIZE * MAP_PARCELLS_X)
#define MAP_BOTTOM (NIBBLER_PADDING_WINDOW_Y + PARCELL_SIZE * MAP_PARCELLS_Y)
#define NBR_OF_WALLS 20
#define COLLISION_EVENT "COLLISION_EVENT"