//
// Created by me0w on 4/2/23.
//

#ifndef ARCADE_SRC_GAMELIBS_SNAKE_COMPONENT_SNAKEMAPENTITY_HPP
#define ARCADE_SRC_GAMELIBS_SNAKE_COMPONENT_SNAKEMAPENTITY_HPP

class SnakeMapEntity {};

#endif // ARCADE_SRC_GAMELIBS_SNAKE_COMPONENT_SNAKEMAPENTITY_HPP
